### ISSUE TITLE
Error trying to install Olympus. Have already installed

### ISSUE THREAD

**Issue by flipdark95** [Surasia/Olympus#1]
Hey man, I keep running into a error trying to enable Olympus after installing it. I followed the instructions for installing texture2ddecoder and pymmh3, but Blender can't find pymmh3.

Here is my system console. 

> Traceback (most recent call last):
>   File "D:\3D Programs\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
>     mod = __import__(module_name)
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\__init__.py", line 73, in <module>
>     from . import ImportCoating
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\ImportCoating.py", line 9, in <module>
>     from . tag_reader.readers.reader_factory import ReaderFactory
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\tag_reader\readers\reader_factory.py", line 8, in <module>
>     from . import generic
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\tag_reader\readers\generic.py", line 5, in <module>
>     from . base_template import BaseTemplate
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\tag_reader\readers\base_template.py", line 8, in <module>
>     from .. tag_parse_control import TagParseControl
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\tag_reader\tag_parse_control.py", line 6, in <module>
>     from . common_tag_types import *
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\tag_reader\common_tag_types.py", line 17, in <module>
>     from . var_names import getStrInMmr3Hash, getMmr3HashFromInt, TAG_NAMES
>   File "C:\Users\wilki\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Olympus\tag_reader\var_names.py", line 10, in <module>
>     import pymmh3 as mmh3
> ModuleNotFoundError: No module named 'pymmh3'

I am running it on Blender 3.3.0.

**Comment by Surasia** [comment]
Follow the initial instructions in the readme file.
